/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook_pro_14.glb -T 
Files: macbook_pro_14.glb [10.85MB] > /home/roninraj/WebstormProjects/gsap_macbook_landing/public/models/macbook_pro_14-transformed.glb [536.23KB] (95%)
*/

import React from 'react'
import {useGLTF, useTexture} from '@react-three/drei'

export default function MacbookPro14Model(props) {
  const { nodes, materials } = useGLTF('/models/macbook_pro_14-transformed.glb');
  const texture = useTexture('/screen.png')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.AQdtiiJfiakvCKx.geometry} material={materials.zNRfbdNyoCOxSDD} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.DmUcWNXfiLPcftc.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bckGBpxpLXNHmCa.geometry} material={materials.GzMrvkTsmRxvOJz} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.fVNvUQeYMdbMNOA.geometry} material={materials.ItKEDAaOJloGKSH} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.IJeReHnhQHJFtgB.geometry} material={materials.xEcnbqMzoZoLkIZ} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.CFihWZPNFpzuzyX.geometry} material={materials.YMmdfGRsPviDXYd} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.dAVNlHAHYLbkxrB.geometry} material={materials.sqkqSXQCeccDMmm} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.WzbwnVztmigkRgn.geometry} material={materials.WiyOPYJEeiHNVjF} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.eFpSjyrDhTgtyuf.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.XodVrcYKiUPGCmX.geometry} material={materials.DthpMXUDOFLFvyk} rotation={[Math.PI / 2, 0, 0]} scale={0.01} >
          <meshBasicMaterial map={texture}/>
      </mesh>
      <mesh geometry={nodes.tfTbkkzhxqpKRgC.geometry} material={materials.HlQwFCAPWzetDQy} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/macbook_pro_14-transformed.glb')
